//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_titles
    {
        public int Emp_id { get; set; }
        public string Job_title { get; set; }
        public System.DateTime From_date { get; set; }
        public System.DateTime To_date { get; set; }
    }
}
